<?php
$adminTitle = 'Email Outbox - EventHub UK';
$adminActive = 'emails';
require __DIR__ . '/_admin_header.php';

$emails = db()->query(
    'SELECT e.*, b.booking_reference
     FROM email_outbox e
     LEFT JOIN bookings b ON b.id = e.related_booking_id
     ORDER BY e.created_at DESC
     LIMIT 50'
)->fetchAll();
?>

<div class="topbar">
    <div>
        <h1>Email Outbox</h1>
        <p>Review login-code and ticket-confirmation emails generated by the system.</p>
    </div>
</div>

<section class="panel" style="margin-bottom: 1.5rem;">
    <h2>Email Delivery</h2>
    <p>
        Emails are queued for review before delivery. System administrators can enable live sending in the application configuration when mail server details are available.
    </p>
</section>

<section class="table-card">
    <h2>Generated Emails</h2>
    <table>
        <thead>
            <tr>
                <th>Created</th>
                <th>Recipient</th>
                <th>Type</th>
                <th>Subject</th>
                <th>Status</th>
                <th>Reference</th>
                <th>Preview</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($emails as $email): ?>
            <tr>
                <td><?= e(date('d M Y H:i', strtotime($email['created_at']))) ?></td>
                <td><?= e($email['recipient_name']) ?><br><small><?= e($email['recipient_email']) ?></small></td>
                <td><span class="status"><?= e(str_replace('_', ' ', $email['email_type'])) ?></span></td>
                <td><?= e($email['subject']) ?></td>
                <td><span class="status <?= e($email['status']) ?>"><?= e($email['status']) ?></span></td>
                <td><?= e($email['booking_reference'] ?? '-') ?></td>
                <td><pre class="email-preview"><?= e($email['body']) ?></pre></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php if (!$emails): ?>
        <p>No emails have been generated yet. Log in or create a booking to populate this outbox.</p>
    <?php endif; ?>
</section>

<?php require __DIR__ . '/_admin_footer.php'; ?>
